#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CosmeticDrinkShaker

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CosmeticDrinkShaker.BP_CosmeticDrinkShaker_C
// 0x0008 (0x02D0 - 0x02C8)
class ABP_CosmeticDrinkShaker_C final : public ASBZCosmeticProp
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CosmeticDrinkShaker_C">();
	}
	static class ABP_CosmeticDrinkShaker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CosmeticDrinkShaker_C>();
	}
};
static_assert(alignof(ABP_CosmeticDrinkShaker_C) == 0x000008, "Wrong alignment on ABP_CosmeticDrinkShaker_C");
static_assert(sizeof(ABP_CosmeticDrinkShaker_C) == 0x0002D0, "Wrong size on ABP_CosmeticDrinkShaker_C");
static_assert(offsetof(ABP_CosmeticDrinkShaker_C, StaticMesh) == 0x0002C8, "Member 'ABP_CosmeticDrinkShaker_C::StaticMesh' has a wrong offset!");

}

