#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Charm_Crystal

#include "Basic.hpp"

#include "BP_Charm_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Charm_Crystal.BP_Charm_Crystal_C
// 0x0000 (0x02D0 - 0x02D0)
class ABP_Charm_Crystal_C final : public ABP_Charm_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Charm_Crystal_C">();
	}
	static class ABP_Charm_Crystal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Charm_Crystal_C>();
	}
};
static_assert(alignof(ABP_Charm_Crystal_C) == 0x000008, "Wrong alignment on ABP_Charm_Crystal_C");
static_assert(sizeof(ABP_Charm_Crystal_C) == 0x0002D0, "Wrong size on ABP_Charm_Crystal_C");

}

