#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DigitPassword_Parent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DigitPassword_Parent.BP_DigitPassword_Parent_C
// 0x0010 (0x02D8 - 0x02C8)
class ABP_DigitPassword_Parent_C : public ASBZCodeNote
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DigitPassword_Parent(int32 EntryPoint);
	void BP_SetCode(class UWidgetComponent* Widget, int32 CodeToShow_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DigitPassword_Parent_C">();
	}
	static class ABP_DigitPassword_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DigitPassword_Parent_C>();
	}
};
static_assert(alignof(ABP_DigitPassword_Parent_C) == 0x000008, "Wrong alignment on ABP_DigitPassword_Parent_C");
static_assert(sizeof(ABP_DigitPassword_Parent_C) == 0x0002D8, "Wrong size on ABP_DigitPassword_Parent_C");
static_assert(offsetof(ABP_DigitPassword_Parent_C, UberGraphFrame) == 0x0002C8, "Member 'ABP_DigitPassword_Parent_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_DigitPassword_Parent_C, StaticMesh) == 0x0002D0, "Member 'ABP_DigitPassword_Parent_C::StaticMesh' has a wrong offset!");

}

