#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Order_TouchReaction

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Order_TouchReaction.BP_Order_TouchReaction_C
// 0x0000 (0x0130 - 0x0130)
class UBP_Order_TouchReaction_C final : public USBZAIOrder
{
public:
	bool ExecPredicate(const class UObject* Owner) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Order_TouchReaction_C">();
	}
	static class UBP_Order_TouchReaction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Order_TouchReaction_C>();
	}
};
static_assert(alignof(UBP_Order_TouchReaction_C) == 0x000008, "Wrong alignment on UBP_Order_TouchReaction_C");
static_assert(sizeof(UBP_Order_TouchReaction_C) == 0x000130, "Wrong size on UBP_Order_TouchReaction_C");

}

