#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pen_01_Body_SmallDestruction

#include "Basic.hpp"

#include "SBZSmallCosmeticDestruction_fading_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Pen_01_Body_SmallDestruction.BP_Pen_01_Body_SmallDestruction_C
// 0x0000 (0x02E0 - 0x02E0)
class ABP_Pen_01_Body_SmallDestruction_C final : public ASBZSmallCosmeticDestruction_fading_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Pen_01_Body_SmallDestruction_C">();
	}
	static class ABP_Pen_01_Body_SmallDestruction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Pen_01_Body_SmallDestruction_C>();
	}
};
static_assert(alignof(ABP_Pen_01_Body_SmallDestruction_C) == 0x000008, "Wrong alignment on ABP_Pen_01_Body_SmallDestruction_C");
static_assert(sizeof(ABP_Pen_01_Body_SmallDestruction_C) == 0x0002E0, "Wrong size on ABP_Pen_01_Body_SmallDestruction_C");

}

