#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_POI_Hostage

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_POI_Hostage.BP_POI_Hostage_C
// 0x0000 (0x02F8 - 0x02F8)
class ABP_POI_Hostage_C final : public ASBZAIPointOfInterest
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_POI_Hostage_C">();
	}
	static class ABP_POI_Hostage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_POI_Hostage_C>();
	}
};
static_assert(alignof(ABP_POI_Hostage_C) == 0x000008, "Wrong alignment on ABP_POI_Hostage_C");
static_assert(sizeof(ABP_POI_Hostage_C) == 0x0002F8, "Wrong size on ABP_POI_Hostage_C");

}

