#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RangedWeapon_Pistol_SE5

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RangedWeapon_Pistol_SE5.BP_RangedWeapon_Pistol_SE5_C
// 0x0000 (0x0750 - 0x0750)
class ABP_RangedWeapon_Pistol_SE5_C final : public ASBZRangedWeapon
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RangedWeapon_Pistol_SE5_C">();
	}
	static class ABP_RangedWeapon_Pistol_SE5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RangedWeapon_Pistol_SE5_C>();
	}
};
static_assert(alignof(ABP_RangedWeapon_Pistol_SE5_C) == 0x000010, "Wrong alignment on ABP_RangedWeapon_Pistol_SE5_C");
static_assert(sizeof(ABP_RangedWeapon_Pistol_SE5_C) == 0x000750, "Wrong size on ABP_RangedWeapon_Pistol_SE5_C");

}

