#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RefractorShield

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RefractorShield.BP_RefractorShield_C
// 0x0008 (0x02F8 - 0x02F0)
class ABP_RefractorShield_C final : public ASBZAIRefractorShield
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_RefractorShield(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RefractorShield_C">();
	}
	static class ABP_RefractorShield_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RefractorShield_C>();
	}
};
static_assert(alignof(ABP_RefractorShield_C) == 0x000008, "Wrong alignment on ABP_RefractorShield_C");
static_assert(sizeof(ABP_RefractorShield_C) == 0x0002F8, "Wrong size on ABP_RefractorShield_C");
static_assert(offsetof(ABP_RefractorShield_C, UberGraphFrame) == 0x0002F0, "Member 'ABP_RefractorShield_C::UberGraphFrame' has a wrong offset!");

}

