#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReactionPredicate_GlobalCooldown_CrewAIMarking

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ReactionPredicate_GlobalCooldown_CrewAIMarking.BP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C
// 0x0000 (0x0048 - 0x0048)
class UBP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C final : public USBZReactionPredicate_GlobalCooldown
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C">();
	}
	static class UBP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C>();
	}
};
static_assert(alignof(UBP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C) == 0x000008, "Wrong alignment on UBP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C");
static_assert(sizeof(UBP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C) == 0x000048, "Wrong size on UBP_ReactionPredicate_GlobalCooldown_CrewAIMarking_C");

}

