#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SecurityRoom

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SecurityRoom.BP_SecurityRoom_C
// 0x0000 (0x03B8 - 0x03B8)
class ABP_SecurityRoom_C final : public ASBZSecurityRoom
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SecurityRoom_C">();
	}
	static class ABP_SecurityRoom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SecurityRoom_C>();
	}
};
static_assert(alignof(ABP_SecurityRoom_C) == 0x000008, "Wrong alignment on ABP_SecurityRoom_C");
static_assert(sizeof(ABP_SecurityRoom_C) == 0x0003B8, "Wrong size on ABP_SecurityRoom_C");

}

