#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SecurityCameraController

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SecurityCameraController.BP_SecurityCameraController_C
// 0x0010 (0x0400 - 0x03F0)
class ABP_SecurityCameraController_C final : public ASBZPerceptionController
{
public:
	class USBZAIVisualDetectionComponent*         SBZAIVisualDetection;                              // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAIPerceptionComponent*                 AIPerception;                                      // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SecurityCameraController_C">();
	}
	static class ABP_SecurityCameraController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SecurityCameraController_C>();
	}
};
static_assert(alignof(ABP_SecurityCameraController_C) == 0x000008, "Wrong alignment on ABP_SecurityCameraController_C");
static_assert(sizeof(ABP_SecurityCameraController_C) == 0x000400, "Wrong size on ABP_SecurityCameraController_C");
static_assert(offsetof(ABP_SecurityCameraController_C, SBZAIVisualDetection) == 0x0003F0, "Member 'ABP_SecurityCameraController_C::SBZAIVisualDetection' has a wrong offset!");
static_assert(offsetof(ABP_SecurityCameraController_C, AIPerception) == 0x0003F8, "Member 'ABP_SecurityCameraController_C::AIPerception' has a wrong offset!");

}

