#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetFinderSorted_Civilian

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TargetFinderSorted_Civilian.BP_TargetFinderSorted_Civilian_C
// 0x0000 (0x0090 - 0x0090)
class UBP_TargetFinderSorted_Civilian_C final : public USBZTargetFinder_TypeDistSorted
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TargetFinderSorted_Civilian_C">();
	}
	static class UBP_TargetFinderSorted_Civilian_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TargetFinderSorted_Civilian_C>();
	}
};
static_assert(alignof(UBP_TargetFinderSorted_Civilian_C) == 0x000008, "Wrong alignment on UBP_TargetFinderSorted_Civilian_C");
static_assert(sizeof(UBP_TargetFinderSorted_Civilian_C) == 0x000090, "Wrong size on UBP_TargetFinderSorted_Civilian_C");

}

