#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WaterCooler_01_Bottle_02

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WaterCooler_01_Bottle_02.BP_WaterCooler_01_Bottle_02_C
// 0x0008 (0x02B0 - 0x02A8)
class ABP_WaterCooler_01_Bottle_02_C final : public AActor
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_WaterCooler_01_Bottle_02_C">();
	}
	static class ABP_WaterCooler_01_Bottle_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WaterCooler_01_Bottle_02_C>();
	}
};
static_assert(alignof(ABP_WaterCooler_01_Bottle_02_C) == 0x000008, "Wrong alignment on ABP_WaterCooler_01_Bottle_02_C");
static_assert(sizeof(ABP_WaterCooler_01_Bottle_02_C) == 0x0002B0, "Wrong size on ABP_WaterCooler_01_Bottle_02_C");
static_assert(offsetof(ABP_WaterCooler_01_Bottle_02_C, StaticMesh) == 0x0002A8, "Member 'ABP_WaterCooler_01_Bottle_02_C::StaticMesh' has a wrong offset!");

}

