#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DA_Melee_Butt_DamageType

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DA_Melee_Butt_DamageType.DA_Melee_Butt_DamageType_C
// 0x0000 (0x0070 - 0x0070)
class UDA_Melee_Butt_DamageType_C final : public USBZMeleeButtDamageType
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DA_Melee_Butt_DamageType_C">();
	}
	static class UDA_Melee_Butt_DamageType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDA_Melee_Butt_DamageType_C>();
	}
};
static_assert(alignof(UDA_Melee_Butt_DamageType_C) == 0x000008, "Wrong alignment on UDA_Melee_Butt_DamageType_C");
static_assert(sizeof(UDA_Melee_Butt_DamageType_C) == 0x000070, "Wrong size on UDA_Melee_Butt_DamageType_C");

}

