#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DIMenuObject

#include "Basic.hpp"

#include "DIMenuObject_classes.hpp"
#include "DIMenuObject_parameters.hpp"


namespace SDK
{

// Function DIMenuObject.DIMenuObject_C.ExecuteUbergraph_DIMenuObject
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADIMenuObject_C::ExecuteUbergraph_DIMenuObject(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DIMenuObject_C", "ExecuteUbergraph_DIMenuObject");

	Params::DIMenuObject_C_ExecuteUbergraph_DIMenuObject Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DIMenuObject.DIMenuObject_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ADIMenuObject_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DIMenuObject_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

