#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Door_opening_setup

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Door_opening_setup.Door_opening_setup
// NumValues: 0x0004
enum class EDoor_opening_setup : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	Door_opening_MAX                         = 3,
};

}

