#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_MaskOnInput

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_MaskOnInput.GA_MaskOnInput_C
// 0x0000 (0x04E8 - 0x04E8)
class UGA_MaskOnInput_C final : public USBZMaskOnInputAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_MaskOnInput_C">();
	}
	static class UGA_MaskOnInput_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_MaskOnInput_C>();
	}
};
static_assert(alignof(UGA_MaskOnInput_C) == 0x000008, "Wrong alignment on UGA_MaskOnInput_C");
static_assert(sizeof(UGA_MaskOnInput_C) == 0x0004E8, "Wrong size on UGA_MaskOnInput_C");

}

