#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UTD_RepositionDefensive

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UTD_RepositionDefensive.UTD_RepositionDefensive_C
// 0x0000 (0x00B0 - 0x00B0)
class UUTD_RepositionDefensive_C final : public USBZAIUtilityDecider
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UTD_RepositionDefensive_C">();
	}
	static class UUTD_RepositionDefensive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUTD_RepositionDefensive_C>();
	}
};
static_assert(alignof(UUTD_RepositionDefensive_C) == 0x000008, "Wrong alignment on UUTD_RepositionDefensive_C");
static_assert(sizeof(UUTD_RepositionDefensive_C) == 0x0000B0, "Wrong size on UUTD_RepositionDefensive_C");

}

