#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UTS_LastAgilityTime

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UTS_LastAgilityTime.UTS_LastAgilityTime_C
// 0x0008 (0x0068 - 0x0060)
class UUTS_LastAgilityTime_C final : public USBZAIUtilityScorer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0060(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_UTS_LastAgilityTime(int32 EntryPoint);

	float CalcScoreBP() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UTS_LastAgilityTime_C">();
	}
	static class UUTS_LastAgilityTime_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUTS_LastAgilityTime_C>();
	}
};
static_assert(alignof(UUTS_LastAgilityTime_C) == 0x000008, "Wrong alignment on UUTS_LastAgilityTime_C");
static_assert(sizeof(UUTS_LastAgilityTime_C) == 0x000068, "Wrong size on UUTS_LastAgilityTime_C");
static_assert(offsetof(UUTS_LastAgilityTime_C, UberGraphFrame) == 0x000060, "Member 'UUTS_LastAgilityTime_C::UberGraphFrame' has a wrong offset!");

}

