#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_SpeedLockpicking

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Starbreeze_structs.hpp"


namespace SDK::Params
{

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking
// 0x01E0 (0x01E0 - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_2;        // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLockpickInstant_ReturnValue;            // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_CreatePlayAnimationProxyObject_Result;    // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimationPlayCallbackProxy*      CallFunc_CreatePlayAnimationProxyObject_ReturnValue; // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_3;        // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_4;        // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_5;        // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x008A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8B[0x1];                                       // 0x008B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x008C(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_3;        // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3MiniGameState                             K2Node_Event_NewState;                             // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00D5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D6[0x2];                                       // 0x00D6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_1;         // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_2;        // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_4;        // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_6;        // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable_2;               // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FA[0x2];                                       // 0x00FA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_1;             // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_2;         // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x3];                                      // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NearlyEqual_FloatFloat_ReturnValue;       // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0112(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_113[0x5];                                      // 0x0113(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_3;         // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_121[0x3];                                      // 0x0121(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_5;        // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_1;          // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NearlyEqual_FloatFloat_ReturnValue_1;     // 0x012C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12D[0x3];                                      // 0x012D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_CreatePlayAnimationProxyObject_Result_1;  // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimationPlayCallbackProxy*      CallFunc_CreatePlayAnimationProxyObject_ReturnValue_1; // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0140(0x0014)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0154(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_155[0x3];                                      // 0x0155(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0158(0x0014)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_NearlyEqual_FloatFloat_ReturnValue_2;     // 0x016C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x016D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_16E[0x2];                                      // 0x016E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_6;        // 0x0170(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue_1;    // 0x0174(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_175[0x3];                                      // 0x0175(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0178(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_18C[0x4];                                      // 0x018C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZMiniGameComponent*                  K2Node_Event_MiniGameComponet;                     // 0x0190(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_2;                     // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESBZDifficulty                                K2Node_Event_HeistDifficulty;                      // 0x0199(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_Event_MiniGameDifficulty;                   // 0x019A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_1;            // 0x019B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x019C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19D[0x3];                                      // 0x019D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_4;         // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_5;         // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_7;        // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_8;        // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_9;        // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_10;       // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_11;       // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsGamePaused_ReturnValue;                 // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking) == 0x000008, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking) == 0x0001E0, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, EntryPoint) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000004, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000008, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000010, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000018, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_PlayAnimationForward_ReturnValue) == 0x000020, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x000028, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue) == 0x000030, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Subtract_FloatFloat_ReturnValue_2) == 0x000038, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Subtract_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Add_FloatFloat_ReturnValue) == 0x00003C, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_1) == 0x000040, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_2) == 0x000048, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_IsLockpickInstant_ReturnValue) == 0x000050, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_IsLockpickInstant_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_RandomFloatInRange_ReturnValue) == 0x000054, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_CreatePlayAnimationProxyObject_Result) == 0x000058, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_CreatePlayAnimationProxyObject_Result' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_CreatePlayAnimationProxyObject_ReturnValue) == 0x000060, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_CreatePlayAnimationProxyObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_IsValid_ReturnValue) == 0x000068, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_3) == 0x000070, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_4) == 0x000078, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_5) == 0x000080, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, Temp_bool_IsClosed_Variable) == 0x000088, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, Temp_bool_Has_Been_Initd_Variable) == 0x000089, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, Temp_bool_Has_Been_Initd_Variable_1) == 0x00008A, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_Event_MyGeometry) == 0x00008C, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_Event_InDeltaTime) == 0x0000C4, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_Event_IsDesignTime) == 0x0000C8, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x0000CC, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Subtract_FloatFloat_ReturnValue_3) == 0x0000D0, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Subtract_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_Event_NewState) == 0x0000D4, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_Event_NewState' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000D5, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetDynamicMaterial_ReturnValue_1) == 0x0000D8, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetDynamicMaterial_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Multiply_FloatFloat_ReturnValue_2) == 0x0000E0, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Multiply_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Subtract_FloatFloat_ReturnValue_4) == 0x0000E4, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Subtract_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Less_FloatFloat_ReturnValue) == 0x0000E8, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_6) == 0x0000F0, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_IsValid_ReturnValue_1) == 0x0000F8, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, Temp_bool_Has_Been_Initd_Variable_2) == 0x0000F9, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::Temp_bool_Has_Been_Initd_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Add_FloatFloat_ReturnValue_1) == 0x0000FC, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Add_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetDynamicMaterial_ReturnValue_2) == 0x000100, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetDynamicMaterial_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000108, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Divide_FloatFloat_ReturnValue) == 0x00010C, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_NearlyEqual_FloatFloat_ReturnValue) == 0x000110, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_NearlyEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Not_PreBool_ReturnValue) == 0x000111, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_BooleanAND_ReturnValue) == 0x000112, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetDynamicMaterial_ReturnValue_3) == 0x000118, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetDynamicMaterial_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, Temp_bool_IsClosed_Variable_1) == 0x000120, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Subtract_FloatFloat_ReturnValue_5) == 0x000124, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Subtract_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Divide_FloatFloat_ReturnValue_1) == 0x000128, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Divide_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_NearlyEqual_FloatFloat_ReturnValue_1) == 0x00012C, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_NearlyEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_CreatePlayAnimationProxyObject_Result_1) == 0x000130, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_CreatePlayAnimationProxyObject_Result_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_CreatePlayAnimationProxyObject_ReturnValue_1) == 0x000138, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_CreatePlayAnimationProxyObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_CreateDelegate_OutputDelegate) == 0x000140, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_IsValid_ReturnValue_2) == 0x000154, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_CreateDelegate_OutputDelegate_1) == 0x000158, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_NearlyEqual_FloatFloat_ReturnValue_2) == 0x00016C, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_NearlyEqual_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_BooleanOR_ReturnValue) == 0x00016D, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Subtract_FloatFloat_ReturnValue_6) == 0x000170, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Subtract_FloatFloat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GreaterEqual_FloatFloat_ReturnValue_1) == 0x000174, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GreaterEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_CreateDelegate_OutputDelegate_2) == 0x000178, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_Event_MiniGameComponet) == 0x000190, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_Event_MiniGameComponet' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, Temp_bool_IsClosed_Variable_2) == 0x000198, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::Temp_bool_IsClosed_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_Event_HeistDifficulty) == 0x000199, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_Event_HeistDifficulty' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, K2Node_Event_MiniGameDifficulty) == 0x00019A, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::K2Node_Event_MiniGameDifficulty' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_Less_FloatFloat_ReturnValue_1) == 0x00019B, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_Less_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00019C, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetDynamicMaterial_ReturnValue_4) == 0x0001A0, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetDynamicMaterial_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetDynamicMaterial_ReturnValue_5) == 0x0001A8, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetDynamicMaterial_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_7) == 0x0001B0, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_8) == 0x0001B8, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_9) == 0x0001C0, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_10) == 0x0001C8, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_GetPlayerController_ReturnValue_11) == 0x0001D0, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_GetPlayerController_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking, CallFunc_IsGamePaused_ReturnValue) == 0x0001D8, "Member 'WBP_UI_Widget_SpeedLockpicking_C_ExecuteUbergraph_WBP_UI_Widget_SpeedLockpicking::CallFunc_IsGamePaused_ReturnValue' has a wrong offset!");

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.OnMiniGameDifficulty
// 0x0002 (0x0002 - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty final
{
public:
	ESBZDifficulty                                HeistDifficulty;                                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         MiniGameDifficulty;                                // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty) == 0x000001, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty) == 0x000002, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty, HeistDifficulty) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty::HeistDifficulty' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty, MiniGameDifficulty) == 0x000001, "Member 'WBP_UI_Widget_SpeedLockpicking_C_OnMiniGameDifficulty::MiniGameDifficulty' has a wrong offset!");

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.OnOwningMiniGameComponent
// 0x0008 (0x0008 - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_OnOwningMiniGameComponent final
{
public:
	class USBZMiniGameComponent*                  MiniGameComponet;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_OnOwningMiniGameComponent) == 0x000008, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_OnOwningMiniGameComponent");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_OnOwningMiniGameComponent) == 0x000008, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_OnOwningMiniGameComponent");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_OnOwningMiniGameComponent, MiniGameComponet) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_OnOwningMiniGameComponent::MiniGameComponet' has a wrong offset!");

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.MiniGameStateChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_MiniGameStateChanged final
{
public:
	EPD3MiniGameState                             NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_MiniGameStateChanged) == 0x000001, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_MiniGameStateChanged");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_MiniGameStateChanged) == 0x000001, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_MiniGameStateChanged");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_MiniGameStateChanged, NewState) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_MiniGameStateChanged::NewState' has a wrong offset!");

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_PreConstruct");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_PreConstruct) == 0x000001, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_PreConstruct");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.Tick
// 0x003C (0x003C - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_Tick) == 0x000004, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_Tick");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_Tick) == 0x00003C, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_Tick");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_Tick, InDeltaTime) == 0x000038, "Member 'WBP_UI_Widget_SpeedLockpicking_C_Tick::InDeltaTime' has a wrong offset!");

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.Get_Image_InteractionGauge_1_Brush_0
// 0x0090 (0x0090 - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_1_Brush_0 final
{
public:
	struct FSlateBrush                            ReturnValue;                                       // 0x0000(0x0090)(Parm, OutParm, ReturnParm)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_1_Brush_0) == 0x000008, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_1_Brush_0");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_1_Brush_0) == 0x000090, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_1_Brush_0");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_1_Brush_0, ReturnValue) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_1_Brush_0::ReturnValue' has a wrong offset!");

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.Get_Image_InteractionGauge_Brush_0
// 0x0090 (0x0090 - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_Brush_0 final
{
public:
	struct FSlateBrush                            ReturnValue;                                       // 0x0000(0x0090)(Parm, OutParm, ReturnParm)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_Brush_0) == 0x000008, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_Brush_0");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_Brush_0) == 0x000090, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_Brush_0");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_Brush_0, ReturnValue) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_Get_Image_InteractionGauge_Brush_0::ReturnValue' has a wrong offset!");

// Function WBP_UI_Widget_SpeedLockpicking.WBP_UI_Widget_SpeedLockpicking_C.NewFunction_0
// 0x0038 (0x0038 - 0x0000)
struct WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0 final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_1;         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_2;         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_3;         // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_4;         // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0) == 0x000008, "Wrong alignment on WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0");
static_assert(sizeof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0) == 0x000038, "Wrong size on WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000000, "Member 'WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0, CallFunc_GetDynamicMaterial_ReturnValue_1) == 0x000008, "Member 'WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0::CallFunc_GetDynamicMaterial_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0, CallFunc_RandomFloatInRange_ReturnValue) == 0x000010, "Member 'WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0, CallFunc_GetDynamicMaterial_ReturnValue_2) == 0x000018, "Member 'WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0::CallFunc_GetDynamicMaterial_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000020, "Member 'WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000024, "Member 'WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0, CallFunc_GetDynamicMaterial_ReturnValue_3) == 0x000028, "Member 'WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0::CallFunc_GetDynamicMaterial_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0, CallFunc_GetDynamicMaterial_ReturnValue_4) == 0x000030, "Member 'WBP_UI_Widget_SpeedLockpicking_C_NewFunction_0::CallFunc_GetDynamicMaterial_ReturnValue_4' has a wrong offset!");

}

