#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_KeyItemContainer

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UI_KeyItemContainer.WBP_UI_KeyItemContainer_C
// 0x0000 (0x02D0 - 0x02D0)
class UWBP_UI_KeyItemContainer_C final : public UPD3KeyItemContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_UI_KeyItemContainer_C">();
	}
	static class UWBP_UI_KeyItemContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UI_KeyItemContainer_C>();
	}
};
static_assert(alignof(UWBP_UI_KeyItemContainer_C) == 0x000008, "Wrong alignment on UWBP_UI_KeyItemContainer_C");
static_assert(sizeof(UWBP_UI_KeyItemContainer_C) == 0x0002D0, "Wrong size on UWBP_UI_KeyItemContainer_C");

}

