#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Blackmarket_Category

#include "Basic.hpp"

#include "WBP_Blackmarket_Category_classes.hpp"
#include "WBP_Blackmarket_Category_parameters.hpp"


namespace SDK
{

// Function WBP_Blackmarket_Category.WBP_Blackmarket_Category_C.ExecuteUbergraph_WBP_Blackmarket_Category
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Blackmarket_Category_C::ExecuteUbergraph_WBP_Blackmarket_Category(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Blackmarket_Category_C", "ExecuteUbergraph_WBP_Blackmarket_Category");

	Params::WBP_Blackmarket_Category_C_ExecuteUbergraph_WBP_Blackmarket_Category Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Blackmarket_Category.WBP_Blackmarket_Category_C.SetStoreCategoryName
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      InCategoryName                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_Blackmarket_Category_C::SetStoreCategoryName(const class FText& InCategoryName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Blackmarket_Category_C", "SetStoreCategoryName");

	Params::WBP_Blackmarket_Category_C_SetStoreCategoryName Parms{};

	Parms.InCategoryName = std::move(InCategoryName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Blackmarket_Category.WBP_Blackmarket_Category_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Blackmarket_Category_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Blackmarket_Category_C", "PreConstruct");

	Params::WBP_Blackmarket_Category_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

