#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_DebugWidgetScreen

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_UI_Widget_DebugWidgetScreen.WBP_UI_Widget_DebugWidgetScreen_C.ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen
// 0x00A8 (0x00A8 - 0x0000)
struct WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZUIManager*                          CallFunc_GetUIManager_ReturnValue;                 // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_1; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZUIManager*                          CallFunc_GetUIManager_ReturnValue_1;               // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZUIManager*                          CallFunc_GetUIManager_ReturnValue_2;               // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerState*                        CallFunc_GetLocalPlayerState_ReturnValue;          // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerState*                        K2Node_DynamicCast_AsSBZPlayer_State;              // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_2; // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_MissionSeed;                          // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_3; // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0068(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen) == 0x000008, "Wrong alignment on WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen");
static_assert(sizeof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen) == 0x0000A8, "Wrong size on WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, EntryPoint) == 0x000000, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000008, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, K2Node_Event_IsDesignTime) == 0x000010, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, CallFunc_GetUIManager_ReturnValue) == 0x000018, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::CallFunc_GetUIManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, CallFunc_CreateDynamicMaterialInstance_ReturnValue_1) == 0x000020, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::CallFunc_CreateDynamicMaterialInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, CallFunc_GetUIManager_ReturnValue_1) == 0x000028, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::CallFunc_GetUIManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, CallFunc_GetUIManager_ReturnValue_2) == 0x000030, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::CallFunc_GetUIManager_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, CallFunc_GetLocalPlayerState_ReturnValue) == 0x000038, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::CallFunc_GetLocalPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, K2Node_DynamicCast_AsSBZPlayer_State) == 0x000040, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::K2Node_DynamicCast_AsSBZPlayer_State' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, CallFunc_CreateDynamicMaterialInstance_ReturnValue_2) == 0x000050, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::CallFunc_CreateDynamicMaterialInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, K2Node_Event_MissionSeed) == 0x000058, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::K2Node_Event_MissionSeed' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, CallFunc_CreateDynamicMaterialInstance_ReturnValue_3) == 0x000060, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::CallFunc_CreateDynamicMaterialInstance_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, K2Node_Event_MyGeometry) == 0x000068, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen, K2Node_Event_InDeltaTime) == 0x0000A0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_ExecuteUbergraph_WBP_UI_Widget_DebugWidgetScreen::K2Node_Event_InDeltaTime' has a wrong offset!");

// Function WBP_UI_Widget_DebugWidgetScreen.WBP_UI_Widget_DebugWidgetScreen_C.Tick
// 0x003C (0x003C - 0x0000)
struct WBP_UI_Widget_DebugWidgetScreen_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Widget_DebugWidgetScreen_C_Tick) == 0x000004, "Wrong alignment on WBP_UI_Widget_DebugWidgetScreen_C_Tick");
static_assert(sizeof(WBP_UI_Widget_DebugWidgetScreen_C_Tick) == 0x00003C, "Wrong size on WBP_UI_Widget_DebugWidgetScreen_C_Tick");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_Tick, InDeltaTime) == 0x000038, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_Tick::InDeltaTime' has a wrong offset!");

// Function WBP_UI_Widget_DebugWidgetScreen.WBP_UI_Widget_DebugWidgetScreen_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_Widget_DebugWidgetScreen_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_UI_Widget_DebugWidgetScreen_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_UI_Widget_DebugWidgetScreen_C_PreConstruct");
static_assert(sizeof(WBP_UI_Widget_DebugWidgetScreen_C_PreConstruct) == 0x000001, "Wrong size on WBP_UI_Widget_DebugWidgetScreen_C_PreConstruct");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_UI_Widget_DebugWidgetScreen.WBP_UI_Widget_DebugWidgetScreen_C.OnMissionSeedSet
// 0x0004 (0x0004 - 0x0000)
struct WBP_UI_Widget_DebugWidgetScreen_C_OnMissionSeedSet final
{
public:
	int32                                         MissionSeed_0;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Widget_DebugWidgetScreen_C_OnMissionSeedSet) == 0x000004, "Wrong alignment on WBP_UI_Widget_DebugWidgetScreen_C_OnMissionSeedSet");
static_assert(sizeof(WBP_UI_Widget_DebugWidgetScreen_C_OnMissionSeedSet) == 0x000004, "Wrong size on WBP_UI_Widget_DebugWidgetScreen_C_OnMissionSeedSet");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_OnMissionSeedSet, MissionSeed_0) == 0x000000, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_OnMissionSeedSet::MissionSeed_0' has a wrong offset!");

// Function WBP_UI_Widget_DebugWidgetScreen.WBP_UI_Widget_DebugWidgetScreen_C.InitializeHudData
// 0x08A8 (0x08A8 - 0x0000)
struct WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData final
{
public:
	class FString                                 SecurityCompanyString;                             // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable;                              // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_1;                            // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESBZMatchmakingProvider                       Temp_byte_Variable;                                // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_2;                            // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_3;                            // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_4;                            // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6A[0x6];                                       // 0x006A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_5;                            // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_6;                            // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_7;                            // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_8;                            // 0x00B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_4;                              // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_9;                            // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_10;                           // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_5;                              // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_11;                           // 0x00F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_6;                              // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_12;                           // 0x0108(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetBuildVersion_ReturnValue;              // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetBranch_ReturnValue;                    // 0x0128(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_13;                           // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0150(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0168(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsStandalone_ReturnValue;                 // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0180(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetNamespace_ReturnValue;                 // 0x0190(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x01A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESBZHostingProvider                           Temp_byte_Variable_1;                              // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x01B8(0x0018)()
	class FString                                 CallFunc_GetSettingsEnvironment_ReturnValue;       // 0x01D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_14;                           // 0x01E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_1;                    // 0x01F0(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x0208(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x0218(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_MakeLiteralString_ReturnValue;            // 0x0228(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_3;              // 0x0238(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsWinGDKActive_ReturnValue;               // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_249[0x7];                                      // 0x0249(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_4;              // 0x0250(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEOSActive_ReturnValue;                  // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_261[0x7];                                      // 0x0261(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_5;              // 0x0268(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPlatformName_ReturnValue;              // 0x0278(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_6;              // 0x0288(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESBZPlatform                                  CallFunc_GetPlatform_ReturnValue;                  // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_7;              // 0x02A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESBZPlatform                                  Temp_byte_Variable_2;                              // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x02B8(0x0018)()
	ESBZHostingProvider                           CallFunc_GetHostingProvider_ReturnValue;           // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D1[0x7];                                      // 0x02D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue_2;                    // 0x02D8(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_2;          // 0x02F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default;                             // 0x0300(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_8;              // 0x0310(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESBZMatchmakingProvider                       CallFunc_GetMatchmakingProvider_ReturnValue;       // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_321[0x7];                                      // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZUIManager*                          CallFunc_GetUIManager_ReturnValue;                 // 0x0328(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default_1;                           // 0x0330(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	const class USBZUIData*                       CallFunc_GetUIData_ReturnValue;                    // 0x0340(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_9;              // 0x0348(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0358(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_359[0x7];                                      // 0x0359(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_10;             // 0x0360(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_7;                              // 0x0370(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_371[0x7];                                      // 0x0371(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_11;             // 0x0378(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_12;             // 0x0388(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_13;             // 0x0398(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ASBZMissionState*                       CallFunc_GetSBZMissionState_ReturnValue;           // 0x03A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x03B0(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x03C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C9[0x7];                                      // 0x03C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASBZMissionState*                       CallFunc_GetSBZMissionState_ReturnValue_1;         // 0x03D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_15;                           // 0x03D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetDifficultyIdx_ReturnValue;             // 0x03E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetValidValue_ReturnValue;                // 0x03E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3EA[0x6];                                      // 0x03EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_16;                           // 0x03F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0400(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetDifficultyText_OutDifficultyText;      // 0x0410(0x0018)()
	bool                                          CallFunc_GetDifficultyText_bHasText;               // 0x0428(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_429[0x7];                                      // 0x0429(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_3;          // 0x0430(0x0018)()
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0448(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_8;                              // 0x0449(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_44A[0x6];                                      // 0x044A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_2;                           // 0x0450(0x0018)(ConstParm)
	class FString                                 K2Node_Select_Default_3;                           // 0x0468(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_3;          // 0x0478(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default_4;                           // 0x0488(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default_5;                           // 0x0498(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetLastMatchID_ReturnValue;               // 0x04A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_3;                    // 0x04B8(0x0018)()
	class ASBZMissionState*                       CallFunc_GetSBZMissionState_ReturnValue_2;         // 0x04D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_4;          // 0x04D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TArray<ESBZSecurityCompany>                   CallFunc_GetSecurityCompanies_ReturnValue;         // 0x04E8(0x0010)(ConstParm, ReferenceParm)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_14;             // 0x04F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESBZSecurityCompany                           CallFunc_Array_Get_Item;                           // 0x0508(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_509[0x7];                                      // 0x0509(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_15;             // 0x0510(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0520(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_524[0x4];                                      // 0x0524(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_4;          // 0x0528(0x0018)()
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0540(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0550(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0554(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0558(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x055C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55D[0x3];                                      // 0x055D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_16;             // 0x0560(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_SelectString_ReturnValue;                 // 0x0570(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_17;             // 0x0580(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_17;                           // 0x0590(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_4;                    // 0x05A0(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_5;          // 0x05B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_1;           // 0x05C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_18;             // 0x05D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_19;             // 0x05E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_5;                    // 0x05F8(0x0018)()
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_20;             // 0x0610(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_6;          // 0x0620(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_21;             // 0x0630(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_22;             // 0x0640(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_23;             // 0x0650(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_24;             // 0x0660(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_5;          // 0x0670(0x0018)()
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_25;             // 0x0688(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_6;          // 0x0698(0x0018)()
	class FString                                 Temp_string_Variable_18;                           // 0x06B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_9;                              // 0x06C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6C1[0x7];                                      // 0x06C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_6;                           // 0x06C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x06D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x06D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6DA[0x6];                                      // 0x06DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_7;                           // 0x06E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default_8;                           // 0x06F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue_1;                   // 0x0700(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_701[0x7];                                      // 0x0701(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_9;                           // 0x0708(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_6;                    // 0x0718(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_7;          // 0x0730(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_26;             // 0x0740(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_27;             // 0x0750(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_28;             // 0x0760(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_7;                    // 0x0770(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_7;          // 0x0788(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_8;          // 0x07A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_29;             // 0x07B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShippingBuild_ReturnValue;                // 0x07C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7C1[0x7];                                      // 0x07C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_30;             // 0x07C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_TestBuild_ReturnValue;                    // 0x07D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7D9[0x7];                                      // 0x07D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_10;                          // 0x07E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_DevelopmentBuild_ReturnValue;             // 0x07F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7F1[0x7];                                      // 0x07F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_11;                          // 0x07F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0808(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_80C[0x4];                                      // 0x080C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_12;                          // 0x0810(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_31;             // 0x0820(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0830(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_831[0x7];                                      // 0x0831(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_32;             // 0x0838(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_33;             // 0x0848(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0858(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_85C[0x4];                                      // 0x085C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_34;             // 0x0860(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_8;          // 0x0870(0x0018)()
	int32                                         CallFunc_GetDebugMatchmakingGroup_ReturnValue;     // 0x0888(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x088C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_88D[0x3];                                      // 0x088D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0890(0x0018)()
};
static_assert(alignof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData) == 0x000008, "Wrong alignment on WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData");
static_assert(sizeof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData) == 0x0008A8, "Wrong size on WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, SecurityCompanyString) == 0x000000, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::SecurityCompanyString' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable) == 0x000010, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_1) == 0x000020, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_byte_Variable) == 0x000030, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_2) == 0x000038, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_3) == 0x000048, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_4) == 0x000058, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable) == 0x000068, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_1) == 0x000069, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_5) == 0x000070, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_6) == 0x000080, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_2) == 0x000090, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_7) == 0x000098, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_3) == 0x0000A8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_8) == 0x0000B0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_4) == 0x0000C0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_9) == 0x0000C8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_10) == 0x0000D8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_10' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_5) == 0x0000E8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_11) == 0x0000F0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_11' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_6) == 0x000100, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_12) == 0x000108, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_12' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetBuildVersion_ReturnValue) == 0x000118, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetBuildVersion_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetBranch_ReturnValue) == 0x000128, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetBranch_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_13) == 0x000138, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_13' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_int_Array_Index_Variable) == 0x000148, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetText_ReturnValue) == 0x000150, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue) == 0x000168, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_IsStandalone_ReturnValue) == 0x000178, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_IsStandalone_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue) == 0x000180, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetNamespace_ReturnValue) == 0x000190, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetNamespace_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_1) == 0x0001A0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_byte_Variable_1) == 0x0001B0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue) == 0x0001B8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetSettingsEnvironment_ReturnValue) == 0x0001D0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetSettingsEnvironment_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_14) == 0x0001E0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_14' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetText_ReturnValue_1) == 0x0001F0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue_1) == 0x000208, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_2) == 0x000218, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_MakeLiteralString_ReturnValue) == 0x000228, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_MakeLiteralString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_3) == 0x000238, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_IsWinGDKActive_ReturnValue) == 0x000248, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_IsWinGDKActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_4) == 0x000250, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_IsEOSActive_ReturnValue) == 0x000260, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_IsEOSActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_5) == 0x000268, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetPlatformName_ReturnValue) == 0x000278, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetPlatformName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_6) == 0x000288, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetPlatform_ReturnValue) == 0x000298, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_7) == 0x0002A0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_byte_Variable_2) == 0x0002B0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue_1) == 0x0002B8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetHostingProvider_ReturnValue) == 0x0002D0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetHostingProvider_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetText_ReturnValue_2) == 0x0002D8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue_2) == 0x0002F0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default) == 0x000300, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_8) == 0x000310, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetMatchmakingProvider_ReturnValue) == 0x000320, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetMatchmakingProvider_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetUIManager_ReturnValue) == 0x000328, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetUIManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_1) == 0x000330, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetUIData_ReturnValue) == 0x000340, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetUIData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_9) == 0x000348, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_IsValid_ReturnValue) == 0x000358, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_10) == 0x000360, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_7) == 0x000370, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_11) == 0x000378, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_12) == 0x000388, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_13) == 0x000398, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetSBZMissionState_ReturnValue) == 0x0003A8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetSBZMissionState_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue_2) == 0x0003B0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_IsValid_ReturnValue_1) == 0x0003C8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetSBZMissionState_ReturnValue_1) == 0x0003D0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetSBZMissionState_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_15) == 0x0003D8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_15' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetDifficultyIdx_ReturnValue) == 0x0003E8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetDifficultyIdx_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetValidValue_ReturnValue) == 0x0003E9, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetValidValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_16) == 0x0003F0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_16' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000400, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetDifficultyText_OutDifficultyText) == 0x000410, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetDifficultyText_OutDifficultyText' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetDifficultyText_bHasText) == 0x000428, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetDifficultyText_bHasText' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue_3) == 0x000430, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_BooleanAND_ReturnValue) == 0x000448, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_8) == 0x000449, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_2) == 0x000450, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_3) == 0x000468, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue_3) == 0x000478, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_4) == 0x000488, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_5) == 0x000498, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetLastMatchID_ReturnValue) == 0x0004A8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetLastMatchID_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetText_ReturnValue_3) == 0x0004B8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetSBZMissionState_ReturnValue_2) == 0x0004D0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetSBZMissionState_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue_4) == 0x0004D8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetSecurityCompanies_ReturnValue) == 0x0004E8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetSecurityCompanies_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_14) == 0x0004F8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Array_Get_Item) == 0x000508, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_15) == 0x000510, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000520, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue_4) == 0x000528, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_IntToString_ReturnValue) == 0x000540, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Array_Length_ReturnValue) == 0x000550, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Array_Length_ReturnValue_1) == 0x000554, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Subtract_IntInt_ReturnValue) == 0x000558, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Less_IntInt_ReturnValue) == 0x00055C, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_16) == 0x000560, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_SelectString_ReturnValue) == 0x000570, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_SelectString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_17) == 0x000580, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_17' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_17) == 0x000590, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_17' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetText_ReturnValue_4) == 0x0005A0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetText_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue_5) == 0x0005B8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_IntToString_ReturnValue_1) == 0x0005C8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_IntToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_18) == 0x0005D8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_18' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_19) == 0x0005E8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_19' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetText_ReturnValue_5) == 0x0005F8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetText_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_20) == 0x000610, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_20' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue_6) == 0x000620, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_21) == 0x000630, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_21' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_22) == 0x000640, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_22' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_23) == 0x000650, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_23' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_24) == 0x000660, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_24' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue_5) == 0x000670, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_25) == 0x000688, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_25' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue_6) == 0x000698, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_string_Variable_18) == 0x0006B0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_string_Variable_18' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_bool_Variable_9) == 0x0006C0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_bool_Variable_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_6) == 0x0006C8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_IsServer_ReturnValue) == 0x0006D8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_IsDedicatedServer_ReturnValue) == 0x0006D9, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_7) == 0x0006E0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_8) == 0x0006F0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_IsServer_ReturnValue_1) == 0x000700, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_IsServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_9) == 0x000708, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetText_ReturnValue_6) == 0x000718, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetText_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue_7) == 0x000730, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_26) == 0x000740, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_26' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_27) == 0x000750, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_27' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_28) == 0x000760, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_28' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetText_ReturnValue_7) == 0x000770, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetText_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue_7) == 0x000788, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_TextToString_ReturnValue_8) == 0x0007A0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_TextToString_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_29) == 0x0007B0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_29' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_ShippingBuild_ReturnValue) == 0x0007C0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_ShippingBuild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_30) == 0x0007C8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_30' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_TestBuild_ReturnValue) == 0x0007D8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_TestBuild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_10) == 0x0007E0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_10' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_DevelopmentBuild_ReturnValue) == 0x0007F0, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_DevelopmentBuild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_11) == 0x0007F8, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_11' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, Temp_int_Loop_Counter_Variable) == 0x000808, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, K2Node_Select_Default_12) == 0x000810, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::K2Node_Select_Default_12' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_31) == 0x000820, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_31' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Less_IntInt_ReturnValue_1) == 0x000830, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_32) == 0x000838, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_32' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_33) == 0x000848, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_33' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Add_IntInt_ReturnValue) == 0x000858, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Concat_StrStr_ReturnValue_34) == 0x000860, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Concat_StrStr_ReturnValue_34' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_StringToText_ReturnValue_8) == 0x000870, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_StringToText_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_GetDebugMatchmakingGroup_ReturnValue) == 0x000888, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_GetDebugMatchmakingGroup_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x00088C, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData, CallFunc_Conv_IntToText_ReturnValue) == 0x000890, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_InitializeHudData::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

// Function WBP_UI_Widget_DebugWidgetScreen.WBP_UI_Widget_DebugWidgetScreen_C.UpdateTime
// 0x0090 (0x0090 - 0x0000)
struct WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime final
{
public:
	int64                                         CallFunc_GetFrameCount_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FDateTime                              CallFunc_Now_ReturnValue;                          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_Int64ToInt_ReturnValue;              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_DateTime_ToString_String;                 // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0030(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0068(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0078(0x0018)()
};
static_assert(alignof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime) == 0x000008, "Wrong alignment on WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime");
static_assert(sizeof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime) == 0x000090, "Wrong size on WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_GetFrameCount_ReturnValue) == 0x000000, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_GetFrameCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_Now_ReturnValue) == 0x000008, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_Now_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_Conv_Int64ToInt_ReturnValue) == 0x000010, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_Conv_Int64ToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_DateTime_ToString_String) == 0x000018, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_DateTime_ToString_String' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_Percent_IntInt_ReturnValue) == 0x000028, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_Conv_IntToText_ReturnValue) == 0x000030, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_Conv_TextToString_ReturnValue) == 0x000048, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_Concat_StrStr_ReturnValue) == 0x000058, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000068, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime, CallFunc_Conv_StringToText_ReturnValue) == 0x000078, "Member 'WBP_UI_Widget_DebugWidgetScreen_C_UpdateTime::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

}

