#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VoIPOverlay

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Starbreeze_structs.hpp"


namespace SDK::Params
{

// Function WBP_VoIPOverlay.WBP_VoIPOverlay_C.ExecuteUbergraph_WBP_VoIPOverlay
// 0x0390 (0x0390 - 0x0000)
struct WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& ChannelName, const class FString& PlayerName, bool bIsTalking)> K2Node_CreateDelegate_OutputDelegate; // 0x0010(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_ChannelName;                    // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_PlayerName;                     // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bIsTalking;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZGameUserSettings*                   CallFunc_GetSBZGameUserSettings_ReturnValue;       // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVoIPEnabled_ReturnValue;                // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_EOSId;                          // 0x0068(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bJoined;                        // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& EOSId, bool bJoined)> K2Node_CreateDelegate_OutputDelegate_1; // 0x007C(0x0014)(ZeroConstructor, NoDestructor)
	struct FSBZLobbyCharacterInfoUi               CallFunc_Array_Get_Item;                           // 0x0090(0x02D8)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0368(0x0014)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_EqualEqual_StriStri_ReturnValue;          // 0x037C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_37D[0x3];                                      // 0x037D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0380(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0384(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0385(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_386[0x2];                                      // 0x0386(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UTLMVoiceChatSubsystem*                 CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0388(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay) == 0x000008, "Wrong alignment on WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay");
static_assert(sizeof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay) == 0x000390, "Wrong size on WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, EntryPoint) == 0x000000, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, Temp_bool_True_if_break_was_hit_Variable) == 0x000004, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, Temp_int_Array_Index_Variable) == 0x000008, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_Not_PreBool_ReturnValue) == 0x00000C, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_Event_IsDesignTime) == 0x00000D, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_CustomEvent_ChannelName) == 0x000028, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_CustomEvent_ChannelName' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_CustomEvent_PlayerName) == 0x000038, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_CustomEvent_PlayerName' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_CustomEvent_bIsTalking) == 0x000048, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_CustomEvent_bIsTalking' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_GetSBZGameUserSettings_ReturnValue) == 0x000050, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_GetSBZGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_IsVoIPEnabled_ReturnValue) == 0x000058, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_IsVoIPEnabled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, Temp_int_Loop_Counter_Variable) == 0x00005C, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_Add_IntInt_ReturnValue) == 0x000060, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_CustomEvent_EOSId) == 0x000068, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_CustomEvent_EOSId' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_CustomEvent_bJoined) == 0x000078, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_CustomEvent_bJoined' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_CreateDelegate_OutputDelegate_1) == 0x00007C, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_Array_Get_Item) == 0x000090, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, K2Node_CreateDelegate_OutputDelegate_2) == 0x000368, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_EqualEqual_StriStri_ReturnValue) == 0x00037C, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_EqualEqual_StriStri_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_Array_Length_ReturnValue) == 0x000380, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_Less_IntInt_ReturnValue) == 0x000384, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_BooleanAND_ReturnValue) == 0x000385, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000388, "Member 'WBP_VoIPOverlay_C_ExecuteUbergraph_WBP_VoIPOverlay::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");

// Function WBP_VoIPOverlay.WBP_VoIPOverlay_C.PlayersUpdated
// 0x0018 (0x0018 - 0x0000)
struct WBP_VoIPOverlay_C_PlayersUpdated final
{
public:
	class FString                                 EOSId;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          bJoined;                                           // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoIPOverlay_C_PlayersUpdated) == 0x000008, "Wrong alignment on WBP_VoIPOverlay_C_PlayersUpdated");
static_assert(sizeof(WBP_VoIPOverlay_C_PlayersUpdated) == 0x000018, "Wrong size on WBP_VoIPOverlay_C_PlayersUpdated");
static_assert(offsetof(WBP_VoIPOverlay_C_PlayersUpdated, EOSId) == 0x000000, "Member 'WBP_VoIPOverlay_C_PlayersUpdated::EOSId' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_PlayersUpdated, bJoined) == 0x000010, "Member 'WBP_VoIPOverlay_C_PlayersUpdated::bJoined' has a wrong offset!");

// Function WBP_VoIPOverlay.WBP_VoIPOverlay_C.PlayerTalkingUpdated
// 0x0028 (0x0028 - 0x0000)
struct WBP_VoIPOverlay_C_PlayerTalkingUpdated final
{
public:
	class FString                                 ChannelName;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 PlayerName;                                        // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          bIsTalking;                                        // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoIPOverlay_C_PlayerTalkingUpdated) == 0x000008, "Wrong alignment on WBP_VoIPOverlay_C_PlayerTalkingUpdated");
static_assert(sizeof(WBP_VoIPOverlay_C_PlayerTalkingUpdated) == 0x000028, "Wrong size on WBP_VoIPOverlay_C_PlayerTalkingUpdated");
static_assert(offsetof(WBP_VoIPOverlay_C_PlayerTalkingUpdated, ChannelName) == 0x000000, "Member 'WBP_VoIPOverlay_C_PlayerTalkingUpdated::ChannelName' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_PlayerTalkingUpdated, PlayerName) == 0x000010, "Member 'WBP_VoIPOverlay_C_PlayerTalkingUpdated::PlayerName' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_PlayerTalkingUpdated, bIsTalking) == 0x000020, "Member 'WBP_VoIPOverlay_C_PlayerTalkingUpdated::bIsTalking' has a wrong offset!");

// Function WBP_VoIPOverlay.WBP_VoIPOverlay_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_VoIPOverlay_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoIPOverlay_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_VoIPOverlay_C_PreConstruct");
static_assert(sizeof(WBP_VoIPOverlay_C_PreConstruct) == 0x000001, "Wrong size on WBP_VoIPOverlay_C_PreConstruct");
static_assert(offsetof(WBP_VoIPOverlay_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_VoIPOverlay_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_VoIPOverlay.WBP_VoIPOverlay_C.UpdateTalkingPlayerList
// 0x05D8 (0x05D8 - 0x0000)
struct WBP_VoIPOverlay_C_UpdateTalkingPlayerList final
{
public:
	class FString                                 PlayerEOSID;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          IsTalking;                                         // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZLobbyCharacterInfoUi               LocalUIInfo;                                       // 0x0018(0x02D8)(Edit, BlueprintVisible)
	struct FSBZLobbyCharacterInfoUi               CallFunc_FindPlayerUIInfo_OutCharacterInfo;        // 0x02F0(0x02D8)()
	bool                                          CallFunc_FindPlayerUIInfo_Found;                   // 0x05C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x05C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5CA[0x2];                                      // 0x05CA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x05CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x05D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x05D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x05D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList) == 0x000008, "Wrong alignment on WBP_VoIPOverlay_C_UpdateTalkingPlayerList");
static_assert(sizeof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList) == 0x0005D8, "Wrong size on WBP_VoIPOverlay_C_UpdateTalkingPlayerList");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, PlayerEOSID) == 0x000000, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::PlayerEOSID' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, IsTalking) == 0x000010, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::IsTalking' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, LocalUIInfo) == 0x000018, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::LocalUIInfo' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, CallFunc_FindPlayerUIInfo_OutCharacterInfo) == 0x0002F0, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::CallFunc_FindPlayerUIInfo_OutCharacterInfo' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, CallFunc_FindPlayerUIInfo_Found) == 0x0005C8, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::CallFunc_FindPlayerUIInfo_Found' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0005C9, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, CallFunc_Array_AddUnique_ReturnValue) == 0x0005CC, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, CallFunc_BooleanAND_ReturnValue) == 0x0005D0, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, CallFunc_Greater_IntInt_ReturnValue) == 0x0005D1, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerList, CallFunc_Array_RemoveItem_ReturnValue) == 0x0005D2, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerList::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");

// Function WBP_VoIPOverlay.WBP_VoIPOverlay_C.FindPlayerUIInfo
// 0x05F8 (0x05F8 - 0x0000)
struct WBP_VoIPOverlay_C_FindPlayerUIInfo final
{
public:
	class FString                                 InEOSID;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	struct FSBZLobbyCharacterInfoUi               OutCharacterInfo;                                  // 0x0010(0x02D8)(Parm, OutParm)
	bool                                          Found;                                             // 0x02E8(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x02E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2EA[0x2];                                      // 0x02EA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x02EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F1[0x3];                                      // 0x02F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x02F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FC[0x4];                                      // 0x02FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSBZLobbyCharacterInfoUi>       CallFunc_GetUiLobbyInfo_OutInfo;                   // 0x0300(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0310(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_314[0x4];                                      // 0x0314(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZLobbyCharacterInfoUi               CallFunc_Array_Get_Item;                           // 0x0318(0x02D8)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x05F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x05F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x05F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoIPOverlay_C_FindPlayerUIInfo) == 0x000008, "Wrong alignment on WBP_VoIPOverlay_C_FindPlayerUIInfo");
static_assert(sizeof(WBP_VoIPOverlay_C_FindPlayerUIInfo) == 0x0005F8, "Wrong size on WBP_VoIPOverlay_C_FindPlayerUIInfo");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, InEOSID) == 0x000000, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::InEOSID' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, OutCharacterInfo) == 0x000010, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::OutCharacterInfo' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, Found) == 0x0002E8, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::Found' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, Temp_bool_True_if_break_was_hit_Variable) == 0x0002E9, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, Temp_int_Array_Index_Variable) == 0x0002EC, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, CallFunc_Not_PreBool_ReturnValue) == 0x0002F0, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, Temp_int_Loop_Counter_Variable) == 0x0002F4, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, CallFunc_Add_IntInt_ReturnValue) == 0x0002F8, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, CallFunc_GetUiLobbyInfo_OutInfo) == 0x000300, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::CallFunc_GetUiLobbyInfo_OutInfo' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, CallFunc_Array_Length_ReturnValue) == 0x000310, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, CallFunc_Array_Get_Item) == 0x000318, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, CallFunc_Less_IntInt_ReturnValue) == 0x0005F0, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, CallFunc_BooleanAND_ReturnValue) == 0x0005F1, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_FindPlayerUIInfo, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x0005F2, "Member 'WBP_VoIPOverlay_C_FindPlayerUIInfo::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");

// Function WBP_VoIPOverlay.WBP_VoIPOverlay_C.CleanActiveArray
// 0x0620 (0x0620 - 0x0000)
struct WBP_VoIPOverlay_C_CleanActiveArray final
{
public:
	TArray<struct FSBZLobbyCharacterInfoUi>       LocalUIActiveTalkers;                              // 0x0000(0x0010)(Edit, BlueprintVisible)
	TArray<class FString>                         LocalActiveTalkers;                                // 0x0010(0x0010)(Edit, BlueprintVisible)
	bool                                          FoundPlayer;                                       // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_23[0x1];                                       // 0x0023(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable_1;        // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBZLobbyCharacterInfoUi               CallFunc_Array_Get_Item;                           // 0x0040(0x02D8)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0318(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x031C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x031D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x031E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31F[0x1];                                      // 0x031F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0320(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_324[0x4];                                      // 0x0324(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSBZLobbyCharacterInfoUi>       CallFunc_GetUiLobbyInfo_OutInfo;                   // 0x0328(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0338(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33C[0x4];                                      // 0x033C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZLobbyCharacterInfoUi               CallFunc_Array_Get_Item_1;                         // 0x0340(0x02D8)()
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0618(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0619(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x061A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoIPOverlay_C_CleanActiveArray) == 0x000008, "Wrong alignment on WBP_VoIPOverlay_C_CleanActiveArray");
static_assert(sizeof(WBP_VoIPOverlay_C_CleanActiveArray) == 0x000620, "Wrong size on WBP_VoIPOverlay_C_CleanActiveArray");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, LocalUIActiveTalkers) == 0x000000, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::LocalUIActiveTalkers' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, LocalActiveTalkers) == 0x000010, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::LocalActiveTalkers' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, FoundPlayer) == 0x000020, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::FoundPlayer' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, Temp_bool_True_if_break_was_hit_Variable) == 0x000021, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Not_PreBool_ReturnValue) == 0x000022, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, Temp_bool_True_if_break_was_hit_Variable_1) == 0x00002C, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::Temp_bool_True_if_break_was_hit_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, Temp_int_Array_Index_Variable) == 0x000030, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Not_PreBool_ReturnValue_1) == 0x000034, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, Temp_int_Array_Index_Variable_1) == 0x000038, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, Temp_int_Loop_Counter_Variable_1) == 0x00003C, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Array_Get_Item) == 0x000040, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Array_Length_ReturnValue) == 0x000318, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Array_RemoveItem_ReturnValue) == 0x00031C, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Less_IntInt_ReturnValue) == 0x00031D, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_BooleanAND_ReturnValue) == 0x00031E, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Add_IntInt_ReturnValue_1) == 0x000320, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_GetUiLobbyInfo_OutInfo) == 0x000328, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_GetUiLobbyInfo_OutInfo' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Array_Length_ReturnValue_1) == 0x000338, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Array_Get_Item_1) == 0x000340, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_Less_IntInt_ReturnValue_1) == 0x000618, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_BooleanAND_ReturnValue_1) == 0x000619, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_CleanActiveArray, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x00061A, "Member 'WBP_VoIPOverlay_C_CleanActiveArray::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");

// Function WBP_VoIPOverlay.WBP_VoIPOverlay_C.UpdateTalkingPlayerDisplay
// 0x0070 (0x0070 - 0x0000)
struct WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay final
{
public:
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0026(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0027(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_Select_Default_1;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_VoIP_C*                            K2Node_Select_Default_2;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextBlock*                             K2Node_Select_Default_3;                           // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_4;                           // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0050(0x0018)()
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay) == 0x000008, "Wrong alignment on WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay");
static_assert(sizeof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay) == 0x000070, "Wrong size on WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_byte_Variable) == 0x000000, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_int_Variable) == 0x000004, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_int_Variable_1) == 0x000008, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_int_Variable_2) == 0x00000C, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_int_Variable_3) == 0x000010, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000014, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_byte_Variable_1) == 0x00001C, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, CallFunc_Greater_IntInt_ReturnValue) == 0x000024, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_bool_Variable) == 0x000025, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, K2Node_Select_Default) == 0x000026, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_byte_Variable_2) == 0x000027, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, K2Node_Select_Default_1) == 0x000028, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, K2Node_Select_Default_2) == 0x000030, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_byte_Variable_3) == 0x000038, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, K2Node_Select_Default_3) == 0x000040, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, Temp_bool_Variable_1) == 0x000048, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, K2Node_Select_Default_4) == 0x000049, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, CallFunc_Conv_StringToText_ReturnValue) == 0x000050, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000068, "Member 'WBP_VoIPOverlay_C_UpdateTalkingPlayerDisplay::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");

}

